/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.nidomiro.nxgradlekotlinshowcase

class Library1 {
    fun someLibraryMethod(): String {
        return "Library1"
    }
}
