/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("gradleappinit.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":libs:shared:testlib1"))
    implementation(project(":libs:shared:testlib2"))
}

application {
    // Define the main class for the application.
    mainClass.set("gradleappinit.app.AppKt")
}
