/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.nidomiro.nx-gradle-kotlin-showcase

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
